server {

    listen 80;

    server_name _;

    location /app1 {

        proxy_pass http://localhost:8081/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        add_header X-Frame-Options SAMEORIGIN;
        add_header X-Content-Type-Options nosniff;
        add_header Referrer-Policy strict-origin-when-cross-origin;

    }

    location /app2 {

        proxy_pass http://localhost:8082/;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

    }

}